# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4046a97d87037e7f2112c7350987621416889fc3ae0365909e63b4f2454fb504616691f5f6bc15c1ae15c911383abb7764f81865c339a9ab98381a3b5ecf23c

test:
  secret_key_base: 9403f55cce9104d7f8132c6acdfd835011b10da133a5c1115b9b3cd85fd254292ffb9857825a89747a1d7e1987ad1a13b8b5ecc059d35ba1b42318b97ec78b25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
